import React, { Component } from 'react'

import CommentList from '../CommentList'
import CommentForm from '../CommentForm'

export default class CommentBox extends Component {
  handleCommentSubmit = (comment) => {
    var comments = this.state.data;
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    comment.id = Date.now();
    var newComments = comments.concat([comment]);
    this.setState({data: newComments});
  };

  constructor() {
    super();
    this.state = {data: []};
  };

  render() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm onCommentSubmit={this.handleCommentSubmit} />
      </div>
    )
  }
}
